trigger:
- main

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: Build 
    displayName: 'Build Job'
    pool:
     vmImage: 'ubuntu-latest'
    steps:
    - bash: echo contents in the working directory are; ls -R $(System.DefaultWorkingDirectory)
    - bash: echo Before copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory) 
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/terraform-manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true
    - bash: echo After copying Contents in Build Artifact Directory; ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'terraform-manifests'
        publishLocation: 'Container'
      